version: '3.7'

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    networks:
      - tutorial-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  volumes-tutorial:
    image: yvyom/docker-volumes-tutorial:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - tutorial-network
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/docker-volume-tutorial?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

networks:
  tutorial-network:

volumes:
  mysql-data:
    driver: local